# Generated by Django 5.2.4 on 2025-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('timesStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
