# Generated by Django 5.2.4 on 2025-07-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=130)),
                ('author', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
