# Generated by Django 5.2.4 on 2025-07-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
